name: qdoas-build
channels:
  - stcorp-forge
  - conda-forge
dependencies:
  - cmake
  - pkg-config
  - coda
  - gsl
  - hdfeos2
  - hdfeos5
  - libnetcdf
  - qt
  - qwt
  - gxx_linux-64
  - libselinux-cos6-x86_64
  - libxdamage-cos6-x86_64
  - libxext-cos6-x86_64
  - libxfixes-cos6-x86_64
  - libxxf86vm-cos6-x86_64
  - mesa-dri-drivers-cos6-x86_64
  - mesa-libegl-devel-cos6-x86_64
  - mesa-libgl-devel-cos6-x86_64
