name: qdoas-build
channels:
  - conda-forge
dependencies:
  - cmake
  - pkg-config
  - libboost-headers
  - coda
  - eigen
  - hdf4
  - hdf5
  - libnetcdf
  - libxmlpp
  - libxml2-devel
  - qt-main
  - qwt
